WITH RECURSIVE ECOLI AS (
    
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL 
    
    UNION ALL
    
    SELECT b.ID, b.PARENT_ID, a.GENERATION + 1
    FROM ECOLI AS a
    JOIN ECOLI_DATA AS b ON a.ID = b.PARENT_ID
)

SELECT ID 
FROM ECOLI
where GENERATION=3
order by ID asc;

